export {default as Homepage} from "./Homepage"
export {default as NotFoundpage} from "./NotFoundpage"
export {default as Showpage} from "./Showpage"
export {default as Showspage} from "./Showspage"
export {default as Searchpage} from "./Searchpage"
